export JRUBY_OPTS="--2.0"
export CONNECT_VBMS_ENV_DIR="/Users/vacomaherj/GitHub/deployment/decrypted_creds"
export CONNECT_VBMS_ENV="test_creds"
export CONNECT_VBMS_URL="***REMOVED***"
export CONNECT_VBMS_KEYFILE="caseflow_test_jks"
export CONNECT_VBMS_SAML="caseflow_test_saml"
export CONNECT_VBMS_KEYPASS="importkey"
