# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40b89e7811264f3c7d7bc923fe4dc32c8a40966131d1c252bc97dfef50a6f6fa076b33ee6fc564d55b0ba9c74b0a303000ec038c2ffe0c912f3928ff7c11a784

test:
  secret_key_base: 9ea33306057676d60966a3b9029787f60fbc1bdbab0bd7f85166ed7aadb5e0942189dc6db08f3018e11d4ccbf6efd1de9228b336ae1542ba6a4f2ceb43231a29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
